imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator:     { fallback: en }
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            true
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'BlackRookTaskBundle:Form:fields.html.twig'


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# Security Exceptions

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true # not needed: listeners are not enabled by default

# Framework Extra Configuration
sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }
    view:    { annotations: true }
    cache:   { annotations: true }

# FOS Rest Configuration
fos_rest:
    routing_loader:
        default_format: html
    view:
        default_engine: twig
        force_redirects:
            html: true
        formats:
            json: true
            xml: true
        templating_formats:
            html: true
        view_response_listener: true
        failed_validation: HTTP_BAD_REQUEST
    exception:
        codes: ~
        messages: ~
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
    format_listener:
        default_priorities: [html, '*/*']
        fallback_format: html
    service:
        view_handler: fos_rest.view_handler.default

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: BlackRook\TaskBundle\Entity\User

services:
    twig.extension.secondsToHuman:
        class: BlackRook\TaskBundle\Twig\Extension\SecondsToHuman
        tags:
            - { name: twig.extension }
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }
    form.type.jsonToArray:
        class: BlackRook\TaskBundle\Form\Type\JsonToArrayType
        tags:
            -  { name: form.type, alias: jsonToArray }
    form.type.yamlToArray:
        class: BlackRook\TaskBundle\Form\Type\YamlToArrayType
        tags:
            -  { name: form.type, alias: yamlToArray }